CREATE TABLE users (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(100) NOT NULL,
                       email VARCHAR(100) NOT NULL UNIQUE,
                       cpf VARCHAR(14) NOT NULL UNIQUE,
                       phone_number VARCHAR(15) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       address VARCHAR(100) NOT NULL,
                       created_at TIMESTAMP NOT NULL
);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role VARCHAR(50) NOT NULL,
                            CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE categories (
                            category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(100) NOT NULL,
                            description VARCHAR(500)
);

CREATE TABLE products (
                          product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          product_name VARCHAR(150) NOT NULL,
                          description VARCHAR(500) NOT NULL,
                          product_price NUMERIC(19, 2) NOT NULL,
                          stock_quantity INTEGER NOT NULL,
                          image VARCHAR(500),
                          weight DOUBLE PRECISION NOT NULL,
                          height INTEGER NOT NULL,
                          width INTEGER NOT NULL,
                          length INTEGER NOT NULL,
                          version BIGINT DEFAULT 0,
                          category_id BIGINT NOT NULL,
                          user_id BIGINT NOT NULL,
                          CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(category_id),
                          CONSTRAINT fk_products_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE cart_items (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            quantity INTEGER NOT NULL,
                            price DOUBLE PRECISION NOT NULL,
                            created_at TIMESTAMP NOT NULL,
                            user_id BIGINT NOT NULL,
                            product_id BIGINT NOT NULL,
                            CONSTRAINT fk_cart_items_user FOREIGN KEY (user_id) REFERENCES users(user_id),
                            CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE orders (
                        order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_date TIMESTAMP NOT NULL,
                        status VARCHAR(50) NOT NULL,
                        total NUMERIC(10, 2),
                        user_id BIGINT NOT NULL,
                        shipping_cost NUMERIC(10, 2) DEFAULT 0.00,
                        CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE order_items (
                             order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             quantity INTEGER NOT NULL,
                             unit_price NUMERIC(10, 2) NOT NULL,
                             subtotal NUMERIC(10, 2) NOT NULL,
                             order_id BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
                             CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE invoices (
                          invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          invoice_number VARCHAR(255) NOT NULL,
                          issue_date TIMESTAMP NOT NULL,
                          due_date TIMESTAMP NOT NULL,
                          total_amount NUMERIC(10, 2) NOT NULL,
                          paid_amount NUMERIC(10, 2) NOT NULL,
                          status VARCHAR(50) NOT NULL,
                          user_id BIGINT,
                          CONSTRAINT fk_invoices_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE payments (
                          payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          amount NUMERIC(10, 2) NOT NULL,
                          payment_date TIMESTAMP NOT NULL,
                          payment_method VARCHAR(50) NOT NULL,
                          status VARCHAR(50) NOT NULL,
                          transaction_id VARCHAR(255) UNIQUE,
                          idempotency_key VARCHAR(255) UNIQUE,
                          order_id BIGINT,
                          invoice_id BIGINT,
                          CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
                          CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id)
);

-- Índices
CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX idx_products_category_id ON products(category_id);
CREATE INDEX idx_products_seller_id ON products(user_id);
CREATE INDEX idx_cart_items_user_id ON cart_items(user_id);
CREATE INDEX idx_cart_items_product_id ON cart_items(product_id);
CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);
CREATE INDEX idx_invoices_user_id ON invoices(user_id);
CREATE INDEX idx_payments_order_id ON payments(order_id);
CREATE INDEX idx_payments_invoice_id ON payments(invoice_id);
CREATE INDEX idx_products_name ON products(product_name);
CREATE INDEX idx_orders_status_date ON orders(status, order_date);
CREATE INDEX idx_payments_method_status ON payments(payment_method, status);
CREATE INDEX idx_categories_name ON categories(name);